// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Device struct {
	ID             string   `json:"id" bson:"_id"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	Specifications []string `json:"specifications"`
}

type NewDevice struct {
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	Specifications []string `json:"specifications"`
}
